# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firewall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('LogPrefix', models.CharField(max_length=50, null=True)),
                ('src_zone', models.CharField(max_length=50, null=True)),
                ('dst_zone', models.CharField(max_length=50, null=True)),
                ('proto', models.CharField(max_length=50, null=True)),
                ('src_ip', models.CharField(max_length=50, null=True)),
                ('src_port', models.CharField(max_length=50, null=True)),
                ('dst_ip', models.CharField(max_length=50, null=True)),
                ('dst_port', models.CharField(max_length=50, null=True)),
                ('nat_osrc_ip', models.CharField(max_length=50, null=True)),
                ('nat_osrc_port', models.CharField(max_length=50, null=True)),
                ('nat_nsrc_ip', models.CharField(max_length=50, null=True)),
                ('nat_nsrc_port', models.CharField(max_length=50, null=True)),
                ('nat_dst_ip', models.CharField(max_length=50, null=True)),
                ('nat_dst_port', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
