# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewall',
            name='src_mac',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
