# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0002_firewall_src_mac'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('user', models.CharField(max_length=50, null=True)),
                ('logged', models.CharField(max_length=50, null=True)),
                ('src_ip', models.CharField(max_length=50, null=True)),
                ('src_type', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FirewallLoginError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('user', models.CharField(max_length=50, null=True)),
                ('src_ip', models.CharField(max_length=50, null=True)),
                ('src_type', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='firewall',
            old_name='LogPrefix',
            new_name='syslog_severity',
        ),
        migrations.AddField(
            model_name='firewall',
            name='topics',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
