# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0004_auto_20170110_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewall_login',
            name='syslog_severity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='firewall_login',
            name='topics',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='firewall_login_error',
            name='syslog_severity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='firewall_login_error',
            name='topics',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
